apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCakNDQWU2Z0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJeU1ERXpNREV4TkRNek0xb1hEVE15TURFeU9URXhORE16TTFvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTXB5Cmt4LzN4QWlmb0VUdnNQNDhtSXRReW81VGVWc1pLYXBYbGlPdUZYYy9YLzYxZFUycUl1TTN5SDhpaUhVY2lIUm8KbUZaNkRXVlN1UXk4eHBuZ3Q2bkFEaFRBS0tOSmJxV040VUlKU2VLcmt0TElRSWJQbUpPVDNRTkxvZmNnR2FScApJZE5oNDVYSjcySjY1Z1o4bm5WWjNEUVVjcS9hV2tzM1kxMWkrM2l5RjVNTzZMTE8rZHJuWEljcE5tS0ErTlNtCmREM00xWk1nMThlRGhuS3NRQU94dGd4cnBMVWh0SThRa2NYUTc5a0I5TmRqOStibXJMU1djWk5BdmN1ak9ZQ2kKUUkrVmpha0hNYys2WVl4dm9POHd2djE1YVl0bnROOWFrRWpPZUYvUGx5eTRDWElORk5HczArQTgxRHVrSlB3eQozeW5rcmhaaW5IeGp3OUowRGY4Q0F3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVcKQkJUN0dLaEg2Q0ZEdFkrK2ZpU0pueUtnWVp5eEp6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUF1dlRSKzBrVApVSGdqeTk0emMxNTRtbkhBd3l5R240cFBRRUpDZU42THMvZ1FXd3FCRHZLL2QxWkFQS3VRUlNXazVRQkl0REYyCnNVdjFMQjNOYjE4c1p6T01TZjlhTC9OdzlxbUV3SHBpZzFKNWQxZVhWbTRCcWNPVjJXcEIyeWwwTmJ3aWFOWnkKaDIrYWlJUklWcmhvN3FJNHV4WTF6TDhvY3Zob1FqdkY0WEtjM0QzcXMvMXZkb2h6N0FPdFBtUVdJQUcrdjZJUgp5TGlqQjRxSjZNU0RLZHJMdngwSmF1KzlHeGl6NVUwNXhqLzJnVDhpMFVFVDVvSTI0akpQSG1rcDJwTGlFR1pzCkFiT0ZyNzM1aTRrRStFcVZoRUU3R2JmZlV0R1dRV0ZlRC9MY2I3cTdCa205WFQreGkwbFd5cDltbm94SHF0RXkKMjkvdTQycjl3Y1Q5MGc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  namespace: Z3Vlc3Rib29r
  token: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklrbFBTV2sxUW5RM1NWWmxSMXB4YVdSd1NqUnRaRmxWVUZsYVZYQnpkbk50T0VFemVGbEdSbEZ1YVZVaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUpuZFdWemRHSnZiMnNpTENKcmRXSmxjbTVsZEdWekxtbHZMM05sY25acFkyVmhZMk52ZFc1MEwzTmxZM0psZEM1dVlXMWxJam9pWkdWbVlYVnNkQzEwYjJ0bGJpMXJjVFZ3YlNJc0ltdDFZbVZ5Ym1WMFpYTXVhVzh2YzJWeWRtbGpaV0ZqWTI5MWJuUXZjMlZ5ZG1salpTMWhZMk52ZFc1MExtNWhiV1VpT2lKa1pXWmhkV3gwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXpaWEoyYVdObExXRmpZMjkxYm5RdWRXbGtJam9pWkdNeE5qZzBNMll0TVdWa1ppMDBaV1UzTFRneE9UY3RNakk1WmpObE1EVm1NbVJqSWl3aWMzVmlJam9pYzNsemRHVnRPbk5sY25acFkyVmhZMk52ZFc1ME9tZDFaWE4wWW05dmF6cGtaV1poZFd4MEluMC5ob2FTUzcxdmJKS0Q0WE9QV3psSDVTRDJSR0pkdnhDc00tOGZzNkZZMUxYV3oxRlhGLS10Nk9LZk92Z0NRVWhCdk5ZcjB1cU8zTFI2OFNkZVRoQjl0UTJWX2VZOUJyYjZiM1pTWkFYWHNCa0ltOGYwZWlTenFiT1dEbVhjZEZMQm5kd2djVjJrOFJEM2VFSWlwYllBaVlxSHZwd25LTkVMWFBwMUhzXzgzM1ZPS0tlS3pVRVljTmJJcmRkemNnWnBncWJsQTNWWVZ5V2J2SGVFUTZSbUViMGllNXc2V2pNbnVMRWpFRU1LY2p3ajhMbVlBdmNXYW9WSDZvdnhKODJfemxlcTZzci1WR25DY2pRRkFMX2dqMk94OV9tSlRKQ09CQ05mTFZHVDI4dGg2RTh2TU4yQlFjd2VUSFJ4LTNzN3VVMHBJejNuQUNaVTNUdkJMWVRSZ2c=
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: dc16843f-1edf-4ee7-8197-229f3e05f2dc
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:ca.crt: {}
        f:namespace: {}
        f:token: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubernetes.io/service-account.name: {}
          f:kubernetes.io/service-account.uid: {}
      f:type: {}
    manager: kube-controller-manager
    operation: Update
    time: "2022-01-31T19:52:53Z"
  name: default-token-kq5pm
  namespace: guestbook
type: kubernetes.io/service-account-token
